name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies in Notes.WebApi
      working-directory: Notes.WebApi
      run: dotnet restore
    - name: Restore dependencies in Notes.Common.EntityModels
      working-directory: Notes.Common.EntityModels
      run: dotnet restore   
    - name: Restore dependencies in Notes.Common.DataContext.Sqlite
      working-directory: Notes.Common.DataContext.Sqlite
      run: dotnet restore       

    - name: Build
      working-directory: Notes.WebApi
      run: dotnet build --no-restore
      
    - name: Testing the Note entity
      working-directory: Notes.Test
      run: dotnet test --no-build --verbosity normal
